/**
 * Live routing view. "The routing decision can never be hidden" — every
 * decision appears here as it is made. The reasons are generated by the
 * routing policy itself, not written for display, so what you read here is
 * the actual rule that fired.
 */

import type { RoutingUpdate } from '../types.ts';

export function Routing({ updates }: { updates: RoutingUpdate[] }): JSX.Element {
  if (updates.length === 0) {
    return <div className="panel muted">No routing decisions yet.</div>;
  }
  return (
    <div className="panel">
      {[...updates].reverse().map((u, i) => (
        <div key={updates.length - i} className="routing-row">
          <div>
            <span className="model">{u.providerId}/{u.modelId}</span>
            {u.role && <span className="role">{u.role}</span>}
            {u.waitedMs > 0 && (
              <span className="tag warn">waited {(u.waitedMs / 1000).toFixed(1)}s</span>
            )}
            {u.estimatedCostUsd > 0 && (
              <span className="tag">~${u.estimatedCostUsd.toFixed(5)}</span>
            )}
          </div>
          <div className="muted reason">{u.reason}</div>
          {u.runnersUp.length > 0 && (
            <div className="muted small">
              runners-up: {u.runnersUp.map((r) => `${r.providerId}/${r.modelId}`).join(', ')}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
